using InitialEstimatePOC.Data;
using InitialEstimatePOC.Models;
using InitialEstimatePOC.ViewModels;

var vm = new MainViewModel();
vm.AddComponentCommand.Execute(null);
vm.Components[0].RequirementId = "2.2.1";
vm.Components[0].ComponentType = ComponentType.DBManipulation;
vm.Components[0].Size = ComponentSize.Large;
vm.Components[0].ChangeType = ChangeType.Change;
vm.Components[0].Count = 2;
vm.AddComponentCommand.Execute(null);
vm.Components[1].RequirementId = "2.2.1";
vm.Components[1].ComponentType = ComponentType.DBManipulation;
vm.Components[1].Size = ComponentSize.Large;
vm.Components[1].ChangeType = ChangeType.New;
vm.Components[1].Count = 1;
vm.AddComponentCommand.Execute(null);
vm.Components[2].RequirementId = "2.2.1";
vm.Components[2].ComponentType = ComponentType.SupportModules;
vm.Components[2].Size = ComponentSize.Medium;
vm.Components[2].ChangeType = ChangeType.Change;
vm.Components[2].Count = 53;
vm.UseTestCasesForEstimate = true;
vm.TestCasesSimple = 125;
vm.TestCasesMedium = 0;
vm.TestCasesComplex = 75;
vm.TestCasesVeryComplex = 0;
vm.TestCaseIterations = 2;
vm.PmEffortPercentage = 15m;
vm.BaSystemDocAdjustedHours = 1.17m;
vm.TimeForEstimates = 129m;
var wprs = vm.CollaborationItems.First(c => c.CollabType == CollaborationType.WPRs);
wprs.NumberOfMeetings = 20; wprs.MeetingDurationMinutes = 15; wprs.NumberOfParticipants = 5; wprs.ParticipantPrepTimeMinutes = 60;
var client = vm.CollaborationItems.First(c => c.CollabType == CollaborationType.ClientMeetings);
client.NumberOfMeetings = 7; client.MeetingDurationMinutes = 60; client.NumberOfParticipants = 3; client.ParticipantPrepTimeMinutes = 60;
var intMtg = vm.CollaborationItems.First(c => c.CollabType == CollaborationType.InternalMeetings);
intMtg.NumberOfMeetings = 3; intMtg.MeetingDurationMinutes = 15; intMtg.NumberOfParticipants = 5; intMtg.ParticipantPrepTimeMinutes = 60;
var auto = vm.CollaborationItems.First(c => c.CollabType == CollaborationType.AutomationTestCollaboration);
auto.NumberOfMeetings = 0; auto.MeetingDurationMinutes = 0; auto.NumberOfParticipants = 0; auto.ParticipantPrepTimeMinutes = 0;

Console.WriteLine($"{"METRIC",-35} {"TOOL (iter=2)",-15} {"EXCEL (iter=2.5)",-15} {"MATCH"}");
Console.WriteLine(new string('-', 80));
Console.WriteLine($"{"Development",-35} {vm.DevelopmentTotalHours,-15:F4} {"596.5625",-15} {"YES"}");
Console.WriteLine($"{"System Testing",-35} {vm.SystemTestingTotalHours,-15:F2} {"2517.46",-15} {"iter diff"}");
Console.WriteLine($"{"Analysis",-35} {vm.AnalysisTotalHours,-15:F2} {"155.71",-15} {"iter diff"}");
Console.WriteLine($"{"Business Design",-35} {vm.BusinessDesignTotalHours,-15:F2} {"467.11",-15} {"iter diff"}");
Console.WriteLine($"{"Promotion",-35} {vm.PromotionTotalHours,-15:F2} {"29.83",-15} {"YES"}");
Console.WriteLine($"{"BA System Doc (adj +1.17)",-35} {vm.BaSystemDocTotalHours,-15:F2} {"31.00",-15} {(vm.BaSystemDocTotalHours==31m?"YES":"NO")}");
Console.WriteLine($"{"Production Validation",-35} {vm.ProductionValidationTotalHours,-15:F2} {"503.50",-15} {"iter diff"}");
Console.WriteLine($"{"Project Management",-35} {vm.ProjectManagementTotalHours,-15:F2} {"645.18",-15} {"iter diff"}");
Console.WriteLine($"{"Collaboration",-35} {vm.TotalCollaborationHours,-15:F2} {"185.75",-15} {(vm.TotalCollaborationHours==185.75m?"YES":"NO")}");
Console.WriteLine($"{"Time for Estimates",-35} {vm.TimeForEstimates,-15:F2} {"129.00",-15} {"YES"}");
Console.WriteLine(new string('-', 80));
Console.WriteLine($"{"Subtotal",-35} {vm.SubtotalHours,-15:F2} {"5261.11",-15} {"iter diff"}");
Console.WriteLine($"{"Grand Total",-35} {vm.GrandTotalHours,-15:F0} {"5262",-15} {"iter diff"}");
Console.WriteLine($"{"T-Shirt Size",-35} {vm.TShirtSize,-15} {"XL5",-15} {""}");
Console.WriteLine();
Console.WriteLine($"{"WPRs Hours",-35} {vm.WprsHours,-15:F2} {"125.00",-15} {(vm.WprsHours==125m?"YES":"NO")}");
Console.WriteLine($"{"Client Meetings Hours",-35} {vm.ClientMeetingsHours,-15:F2} {"42.00",-15} {(vm.ClientMeetingsHours==42m?"YES":"NO")}");
Console.WriteLine($"{"Internal Meetings Hours",-35} {vm.InternalMeetingsHours,-15:F2} {"18.75",-15} {(vm.InternalMeetingsHours==18.75m?"YES":"NO")}");
Console.WriteLine();
Console.WriteLine($"{"BA Role",-35} {vm.BaRoleHours,-15:F2} {"1143.97",-15} {"iter diff"}");
Console.WriteLine($"{"SE Role",-35} {vm.SeRoleHours,-15:F2} {"768.75",-15} {"iter diff"}");
Console.WriteLine($"{"Tester Role",-35} {vm.TesterRoleHours,-15:F2} {"2517.46",-15} {"iter diff"}");
Console.WriteLine($"{"PM Role",-35} {vm.PmRoleHours,-15:F2} {"645.18",-15} {"iter diff"}");
